feat : マッチング設定画面の追加
Aiki-Toyokawa/Tornado2023-Team3 pull request #31
Opened 2023-08-29 16:56 UTC by Aiki-Toyokawa

マッチング設定画面である、
MatchingSettingsPage.jsx
MatchingSettingsPage.css
と画像3枚を追加した。

2023-08-31 06:37 UTC, yuporon commented
https://github.com/Aiki-Toyokawa/Tornado2023-Team3/pull/30
これをこのプルリクにかく

2023-08-31 06:39 UTC, yuporon requested changes
https://github.com/Aiki-Toyokawa/Tornado2023-Team3/pull/26

このプルリクだとちゃんと日付とか動くように、これも動くようにして欲しい。
同じ画面やき、どっちかを修正してUIいい感じにしてほしみ
よくわからんかったらきいてね

2023-08-31 06:44 UTC, Aiki-Toyokawa commented
了解！

2023-09-05 06:08 UTC, yuporon commented
変わってないよ〜

Uploading 画面収録 2023-09-05 15.08.23.mov…

2023-09-05 06:11 UTC, yuporon commented
愛ちゃんが作ったやつは
`http://localhost:3001/match-settings`
で今元々あるやつ（同じ画面だからどっちか残す）は
`http://localhost:3001/match-input`
よ

2025-01-31 09:35 UTC, closed without merging